# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dbcomponent_pb2 as dbcomponent__pb2


class DBComponentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVillano = channel.unary_unary(
                '/dbcomponent.DBComponent/CreateVillano',
                request_serializer=dbcomponent__pb2.VillanoRequest.SerializeToString,
                response_deserializer=dbcomponent__pb2.VillanoResponse.FromString,
                )


class DBComponentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateVillano(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBComponentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVillano': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVillano,
                    request_deserializer=dbcomponent__pb2.VillanoRequest.FromString,
                    response_serializer=dbcomponent__pb2.VillanoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbcomponent.DBComponent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DBComponent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateVillano(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbcomponent.DBComponent/CreateVillano',
            dbcomponent__pb2.VillanoRequest.SerializeToString,
            dbcomponent__pb2.VillanoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
