# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbcomponent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x62\x63omponent.proto\x12\x0b\x64\x62\x63omponent\"?\n\x0eVillanoRequest\x12\x16\n\x0enombre_villano\x18\x01 \x01(\t\x12\x15\n\rfecha_ingreso\x18\x02 \x01(\t\"\"\n\x0fVillanoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2[\n\x0b\x44\x42\x43omponent\x12L\n\rCreateVillano\x12\x1b.dbcomponent.VillanoRequest\x1a\x1c.dbcomponent.VillanoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbcomponent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VILLANOREQUEST']._serialized_start=34
  _globals['_VILLANOREQUEST']._serialized_end=97
  _globals['_VILLANORESPONSE']._serialized_start=99
  _globals['_VILLANORESPONSE']._serialized_end=133
  _globals['_DBCOMPONENT']._serialized_start=135
  _globals['_DBCOMPONENT']._serialized_end=226
# @@protoc_insertion_point(module_scope)
